### ISSUE TITLE
harmony version & io.js compatibility

### ISSUE THREAD

**Issue by ataraxus** [jlipps/monocle-js#8]
I recently tried to use monocle-js with the current release (1.0.1) of io.js and got the following error: 
```
/monocle-js/node_modules/harmony-reflect/reflect.js:2238
var revokedHandler = Proxy.create({
                     ^
ReferenceError: Proxy is not defined
    at /elasticsearch/node_modules/monocle-js/node_modules/harmony-reflect/reflect.js:2238:22
    at Object.<anonymous> (/elasticsearch/node_modules/monocle-js/node_modules/harmony-reflect/reflect.js:2318:2)
    at Module._compile (module.js:446:26)
    at Object.Module._extensions..js (module.js:464:10)
    at Module.load (module.js:341:32)
    at Function.Module._load (module.js:296:12)
    at Module.require (module.js:351:17)
    at require (module.js:370:17)
    at Object.<anonymous> (/elasticsearch/node_modules/monocle-js/lib/monocle.js:14:3)
    at Module._compile (module.js:446:26)
```

since io.js supports large chunks of ES6 I expected it to work without any additional parameters. 
I've found two workarounds and would like to know which one is the better one: 

*Bump monocle-js' harmony-reflect version*
```
package.js
+"harmony-reflect": "~1.1.1"
- "harmony-reflect": "~0.0.13"
```
If this dep is upgraded you can use monocle-js (as I can say) without any further io.js parameters.

*Use io.js parameter*
```
iojs --harmony-proxies server.js 
```

what do you recommend?

**Comment by jlipps** [comment]
Thanks for this! And... why not both strategies? Certainly there's no harm in bumping the dep version, and if you're using iojs, why not use the native Proxy?

**Comment by jlipps** [comment]
ok, 1.0.1 is out with these fixes.

**Comment by ataraxus** [comment]
Thanks, that was fast!
